apiVersion : apps/v1
kind: Deployment
metadata:
  name: javasample 
  labels:
    app: javasample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javasample
  template:
    metadata:
      labels:
        app: javasample 
    spec:
      containers:
        - name: javasample 
          image: desattir.azurecr.io/javasample
          ports:
          - containerPort: 80